In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [3]:
arr.ndim

1

In [4]:
arr =np.array(34)
arr.ndim

0

In [5]:
a = np.array([[[[]]]])
a.ndim
a.shape

(1, 1, 1, 0)

In [6]:
range = np.arange(1,10, 2)

In [7]:
range

array([1, 3, 5, 7, 9])

In [8]:
arr = np.linspace(0,1,10) #start, stop, number of values
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [9]:
arr = np.logspace(1, 3, 2) #logarithmic scale array -> 10^1 -> 10^3 ... 3 points
arr

array([  10., 1000.])

In [10]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [11]:
arr = np.zeros([2,3]) #array full of zeros
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
arr = np.ones([4,2]) #array full of ones.
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
arr = np.full(10, 2) #-> create an array full of any value
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
arr = np.full([2,4], 7.1) #[row, column], default value
arr

array([[7.1, 7.1, 7.1, 7.1],
       [7.1, 7.1, 7.1, 7.1]])

In [15]:
arr = np.empty([2,3]) #Uninitialized array -> create an array without setting any values
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
arr = np.random.rand(10)
arr

array([0.05305696, 0.86251745, 0.26848166, 0.91631247, 0.60566076,
       0.02338391, 0.1279834 , 0.83322587, 0.02479829, 0.66415448])

In [17]:
arr = np.random.rand(2,3)
arr

array([[0.70084439, 0.46885291, 0.17857549],
       [0.99620099, 0.96989509, 0.06836345]])

In [18]:
arr = np.random.randn(2,3)
arr 

array([[ 0.0633073 , -0.8344628 , -0.87321578],
       [ 1.45350158,  1.04643045, -0.99953153]])

In [129]:
a#-> random integersrr = np.random.randint(10, 100) #->start, stop, dimension/number of values
arr

array([1, 2, 3])

In [19]:
arr = np.random.randint(10, 100, size = (2,3)) #->start, stop, dimension/number of values
arr

array([[70, 84, 82],
       [98, 74, 82]], dtype=int32)

In [20]:
arr = np.array([1,2,3.1,4,5])
arr

array([1. , 2. , 3.1, 4. , 5. ])

In [21]:
arr.dtype

dtype('float64')

In [22]:
lst = ["string", 1, 2, 5.6]
arr = np.array(lst)
arr

array(['string', '1', '2', '5.6'], dtype='<U32')

In [23]:
arr = np.array(["1",2,3.1,4,5])
arr

array(['1', '2', '3.1', '4', '5'], dtype='<U32')

In [24]:
arr.dtype

dtype('<U32')

In [25]:
arr = np.array([1.1, 2.6 , 3 , 4], dtype = np.int64)

In [26]:
arr.dtype

dtype('int64')

In [27]:
arr

array([1, 2, 3, 4])

In [28]:
arr = np.array([1,2,3])
arr.dtype

dtype('int64')

In [29]:
new_arr = arr.astype(np.float64)
new_arr

array([1., 2., 3.])

In [30]:
new_arr.dtype

dtype('float64')

In [31]:
new_arr2 = new_arr.astype(np.int64)
new_arr2

array([1, 2, 3])

In [32]:
arr = np.array([[1,2,3],
                [4,5,6]])

In [33]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
arr.ndim

2

In [35]:
arr.size

6

In [36]:
arr.itemsize

8

In [37]:
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [38]:
reshape2 = reshaped.reshape(3,2)

In [39]:
reshape2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
ravel = reshape2.ravel()
ravel

array([1, 2, 3, 4, 5, 6])

In [41]:
ravel[0] = 100
print(ravel)
print(reshape2)

[100   2   3   4   5   6]
[[100   2]
 [  3   4]
 [  5   6]]


In [42]:
flat = reshape2.flatten()
flat

array([100,   2,   3,   4,   5,   6])

In [43]:
flat[0] = 1

In [44]:
flat

array([1, 2, 3, 4, 5, 6])

In [45]:
reshape2

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [46]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [47]:
print(a+b)

[5 7 9]


In [48]:
print(b-a)

[3 3 3]


In [49]:
print(a/b)

[0.25 0.4  0.5 ]


In [50]:
print(b//a)

[4 2 2]


In [51]:
print(a*b)

[ 4 10 18]


In [52]:
print(b%a)

[0 1 0]


In [53]:
print(a**2)

[1 4 9]


In [54]:
arr = np.array([1,4,9,16])

In [55]:
print(np.sqrt(arr))

[1. 2. 3. 4.]


In [56]:
print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [57]:
angles = np.array([0, np.pi/2, np.pi])
print(np.sin(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [58]:
a = [1,2,3,4,5]

In [59]:
a[-1:-4: -1]

[5, 4, 3]

In [61]:
arr = np.array([10,20,30,40,50])
# indexes = 0, 2, 4
arr[::2]

array([10, 30, 50])

In [62]:
print(arr[-1])

50


In [63]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [64]:
print(matrix[0:2, :])

[[1 2 3]
 [4 5 6]]


In [65]:
print(matrix[1: , 1:])

[[5 6]
 [8 9]]


In [66]:
arr = np.array([10,20,30,40,50])
ind = [0, 2]
print(np.take(arr, ind))

[10 30]


In [67]:
arr= np.array([[1,2], [3,4]])

In [68]:
for x in np.nditer(arr):
  print(x, end = " ")

1 2 3 4 

In [69]:
for ind, x in np.ndenumerate(arr):
  print(ind, x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [70]:
arr = np.array([1,2,3,4,5])
view = arr[1:3]
view

array([2, 3])

In [71]:
view[0] = 200

In [72]:
view

array([200,   3])

In [73]:
arr

array([  1, 200,   3,   4,   5])

In [74]:
copy = arr[1:3].copy()
copy

array([200,   3])

In [75]:
copy[0] = 2
copy

array([2, 3])

In [76]:
arr

array([  1, 200,   3,   4,   5])

In [77]:
arr = np.array([[1,2], [3,4]])
arr

array([[1, 2],
       [3, 4]])

In [78]:
print(arr.transpose())

[[1 3]
 [2 4]]


In [79]:
arr = np.array([[[1,2], [3,4]]])
arr.shape

(1, 2, 2)

In [80]:
swap = np.swapaxes(arr, 0, 1)
swap.shape

(2, 1, 2)

In [81]:
a = np.array([1,2])
b = np.array([3,4])

In [82]:
combine = np.concatenate((a,b))
combine

array([1, 2, 3, 4])

In [83]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

In [84]:
print(np.vstack((arr1, arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [85]:
print(np.hstack((arr1, arr2)))

[[1 2 5 6]
 [3 4 7 8]]


In [86]:
print(np.stack((arr1, arr2), axis = 0))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [87]:
print(np.stack((arr1, arr2), axis = 1))

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [88]:
arr1 = np.array([[1,2], [3,4], [5,6], [7,8]])

In [89]:
arr1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [90]:
print(np.split(arr1, 4))

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]


In [91]:
print(np.hsplit(arr1, 2))

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


In [92]:
arr = np.array([1,2,3])
print(np.repeat(arr,3))

[1 1 1 2 2 2 3 3 3]


In [93]:
print(np.tile(arr, 2))

[1 2 3 1 2 3]


In [94]:
arr = np.array([1,2,3])
print(np.sum(arr))

6


In [95]:
np.mean(arr)

np.float64(2.0)

In [96]:
np.median(arr)

np.float64(2.0)

In [97]:
np.std(arr)

np.float64(0.816496580927726)

In [98]:
np.var(arr)

np.float64(0.6666666666666666)

In [99]:
np.max(arr)

np.int64(3)

In [100]:
np.min(arr)

np.int64(1)

In [101]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
print(np.sum(matrix, axis = 0))

[12 15 18]


In [103]:
arr

array([1, 2, 3])

In [104]:
print(np.cumsum(arr))

[1 3 6]


In [105]:
print(np.cumprod(arr))

[1 2 6]


In [106]:
arr

array([1, 2, 3])

In [107]:
result = np.where(arr <2, "low", "high")

In [108]:
result

array(['low', 'high', 'high'], dtype='<U4')

In [109]:
arr

array([1, 2, 3])

In [110]:
arr

array([1, 2, 3])

In [111]:
print(np.argwhere(arr>0))

[[0]
 [1]
 [2]]


In [112]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [113]:
print(np.argwhere(matrix> 5))

[[1 2]
 [2 0]
 [2 1]
 [2 2]]


In [114]:
arr

array([1, 2, 3])

In [115]:
mask = np.logical_and(arr > 3, arr < 6)

In [116]:
arr[mask]

array([], dtype=int64)

In [117]:
mask = np.logical_or(arr < 4, arr > 5)
mask

array([ True,  True,  True])

In [118]:
arr[mask]

array([1, 2, 3])

In [119]:
arr2 = np.array([0, 1, 5, 0, 5])
arr2

array([0, 1, 5, 0, 5])

In [120]:
print(np.nonzero(arr2))

(array([1, 2, 4]),)


In [121]:
image = np.array([[200, 150], [100, 250]])
image.shape

(2, 2)

In [134]:
brightness = image + 50
brightness

array([[250, 200],
       [150, 300]])

In [130]:
import numpy as np
def square(x):
  return x*x

In [124]:
arr

array([1, 2, 3])

In [131]:
print(vfunc(arr))

NameError: name 'vfunc' is not defined

In [132]:
a = np.array([1, 2, np.nan, 4])

In [133]:
a

array([ 1.,  2., nan,  4.])

In [135]:
b = np.array([1, np.nan, np.inf, 10.2, 40])

In [136]:
print(np.isinf(b))

[False False  True False False]


In [137]:
new_b = np.nan_to_num(b)

In [138]:
new_b

array([1.00000000e+000, 0.00000000e+000, 1.79769313e+308, 1.02000000e+001,
       4.00000000e+001])